// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtF-hD0t-jAuqPzHBVAVAcM1AdJOF9tIo',
    appId: '1:933913866415:web:45368cc3933976cc9a245a',
    messagingSenderId: '933913866415',
    projectId: 'net-finance-hub-9d48b',
    authDomain: 'net-finance-hub-9d48b.firebaseapp.com',
    storageBucket: 'net-finance-hub-9d48b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOXzRcl2bckTHNJO8CP6aIndQb594hHA',
    appId: '1:933913866415:android:590a44fb048cf36a9a245a',
    messagingSenderId: '933913866415',
    projectId: 'net-finance-hub-9d48b',
    storageBucket: 'net-finance-hub-9d48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcG3rZ6J6V89UXYSX1VbhTI5eLw6WT5nA',
    appId: '1:933913866415:ios:0a8e27945fbfeb299a245a',
    messagingSenderId: '933913866415',
    projectId: 'net-finance-hub-9d48b',
    storageBucket: 'net-finance-hub-9d48b.appspot.com',
    iosBundleId: 'com.example.netFinanceHub',
  );
}
